// AUTOGENERATED by export_strict_cpp.py — do not hand-edit.
// Companion binary: ml_recommender_weights.bin

#pragma once
#include <cstdint>
#include <cstddef>

namespace origami {
namespace ml_recommender {

static constexpr uint32_t kBinVersion       = 2;  // BIN_VERSION=2 = BF16
static constexpr uint32_t kQueryDim         = 64;
static constexpr uint32_t kItemDim          = 20;
static constexpr uint32_t kInterDim         = 47;
static constexpr uint32_t kNumClustersTotal   = 80;
static constexpr uint32_t kNumClustersTrained = 80;
static constexpr double   kWb               = 0.3;

// Path of companion binary (resolve relative to this header at build time)
static constexpr const char* kWeightsBinFilename = "ml_recommender_weights.bin";

// Cluster centroids (n_clusters_total * 4 float32) live at offset:
static constexpr size_t kCentroidOffset = 36;  // header bytes

}  // namespace ml_recommender
}  // namespace origami
